/*
 * @solvedac/unofficial-documentation
 *
 * 이 프로젝트는 [solved.ac](https://solved.ac/) API를 문서화하는 커뮤니티 프로젝트입니다.  이 저장소는 원작자의 요청에 따라 언제든 지워질 수 있으며, 현재 API와 일치하지 않을 수도 있는 점 양해 부탁드립니다.   <sup>   solved.ac 서비스는 shiftpsh가 기획·개발·디자인·운영하는 프로젝트로,   이 저장소와는 solved.ac의 API를 문서화해둔 것 이외에는 아무런 관련이 없습니다. </sup>   [GitHub에서 보기](https://github.com/solvedac/unofficial-documentation)   **주의**: (2023/03/08~) CORS 문제로 인해 API는 사이트 내에서 호출할 수 없으므로 별도 도구를 이용해주십시오. ([#51](https://github.com/solvedac/unofficial-documentation/issues/51)) <br> **참고**: 본 저장소를 내려받고, `pnpm dev`를 실행하시면 로컬 개발 서버를 프록시로 삼아 CORS를 무시할 수 있습니다.    ![@solvedac/unofficial-documentation banner](/unofficial-documentation/assets/solvedac-ud-compact.png)
 *
 * The version of the OpenAPI document: 3.2024.03+b1
 * Contact: me@ranolp.dev
 * Generated by: https://openapi-generator.tech
 */

/// BackgroundAuthor : 배경을 작업한 작가입니다.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackgroundAuthor {
    /// 작가 고유 ID입니다.
    #[serde(rename = "authorId")]
    pub author_id: String,
    /// 수행한 역할입니다.
    #[serde(rename = "role")]
    pub role: String,
    /// 작가 홈페이지로 가는 하이퍼링크입니다.
    #[serde(rename = "authorUrl", skip_serializing_if = "Option::is_none")]
    pub author_url: Option<String>,
    /// 작가의 solved.ac 핸들입니다.
    #[serde(rename = "handle", skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    /// 작가의 Twitter ID입니다.
    #[serde(rename = "twitter", skip_serializing_if = "Option::is_none")]
    pub twitter: Option<String>,
    /// 작가의 인스타그램 ID입니다.
    #[serde(rename = "instagram", skip_serializing_if = "Option::is_none")]
    pub instagram: Option<String>,
    /// 작가의 표시 이름입니다.
    #[serde(rename = "displayName")]
    pub display_name: String,
}

impl BackgroundAuthor {
    /// 배경을 작업한 작가입니다.
    pub fn new(author_id: String, role: String, display_name: String) -> BackgroundAuthor {
        BackgroundAuthor {
            author_id,
            role,
            author_url: None,
            handle: None,
            twitter: None,
            instagram: None,
            display_name,
        }
    }
}


