/*
 * @solvedac/unofficial-documentation
 *
 * 이 프로젝트는 [solved.ac](https://solved.ac/) API를 문서화하는 커뮤니티 프로젝트입니다. 이 저장소는 원작자의 요청에 따라 언제든 지워질 수 있으며, 현재 API와 일치하지 않을 수도 있는 점 양해 부탁드립니다.  <sup>   solved.ac 서비스는 shiftpsh가 기획·개발·디자인·운영하는 프로젝트로,   이 저장소와는 solved.ac의 API를 문서화해둔 것 이외에는 아무런 관련이 없습니다. </sup>  **주의**: account 하위 루트를 탐색할 경우, 현재 로그인된 solvedacToken이 노출·오용될 수 있으니 주의하십시오.  [GitHub에서 보기](https://github.com/solvedac/unofficial-documentation)  ![@solvedac/unofficial-documentation banner](./assets/solvedac-ud-compact.png) 
 *
 * The version of the OpenAPI document: 3.2022.02+b1
 * Contact: public.ranolp@gmail.com
 * Generated by: https://openapi-generator.tech
 */

/// CoinshopProduct : 코인샵에서 판매하고 있는 상품입니다. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CoinshopProduct {
    /// 상품의 ID입니다.
    #[serde(rename = "skuId")]
    pub sku_id: i32,
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<Box<crate::models::Item>>,
    /// 1회 구매에 획득하는 개수입니다.
    #[serde(rename = "units", skip_serializing_if = "Option::is_none")]
    pub units: Option<i32>,
    /// 가격입니다. 별조각의 경우 나누기 100을 해야 표시 가격이 됩니다.
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<i32>,
    /// 가격의 단위입니다.
    #[serde(rename = "priceUnit", skip_serializing_if = "Option::is_none")]
    pub price_unit: Option<PriceUnit>,
    /// 아이템 사용 시간의 제한 여부입니다.
    #[serde(rename = "itemUseTimeLimited", skip_serializing_if = "Option::is_none")]
    pub item_use_time_limited: Option<bool>,
    /// 아이템 구매 시간의 제한 여부입니다.
    #[serde(rename = "itemSellTimeLimited", skip_serializing_if = "Option::is_none")]
    pub item_sell_time_limited: Option<bool>,
}

impl CoinshopProduct {
    /// 코인샵에서 판매하고 있는 상품입니다. 
    pub fn new(sku_id: i32) -> CoinshopProduct {
        CoinshopProduct {
            sku_id,
            item: None,
            units: None,
            price: None,
            price_unit: None,
            item_use_time_limited: None,
            item_sell_time_limited: None,
        }
    }
}

/// 가격의 단위입니다.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PriceUnit {
    #[serde(rename = "coins")]
    Coins,
    #[serde(rename = "stardusts")]
    Stardusts,
}

