/*
 * @solvedac/unofficial-documentation
 *
 * 이 프로젝트는 [solved.ac](https://solved.ac/) API를 문서화하는 커뮤니티 프로젝트입니다. 이 저장소는 원작자의 요청에 따라 언제든 지워질 수 있으며, 현재 API와 일치하지 않을 수도 있는 점 양해 부탁드립니다.  <sup>   solved.ac 서비스는 shiftpsh가 기획·개발·디자인·운영하는 프로젝트로,   이 저장소와는 solved.ac의 API를 문서화해둔 것 이외에는 아무런 관련이 없습니다. </sup>  **주의**: account 하위 루트를 탐색할 경우, 현재 로그인된 solvedacToken이 노출·오용될 수 있으니 주의하십시오.  [GitHub에서 보기](https://github.com/solvedac/unofficial-documentation)  ![@solvedac/unofficial-documentation banner](./assets/solvedac-ud-compact.png) 
 *
 * The version of the OpenAPI document: 3.2022.02+b1
 * Contact: public.ranolp@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20012 {
    #[serde(rename = "autocomplete", skip_serializing_if = "Option::is_none")]
    pub autocomplete: Option<Vec<crate::models::InlineResponse20012Autocomplete>>,
    /// 찾은 문제 목록입니다.
    #[serde(rename = "problems", skip_serializing_if = "Option::is_none")]
    pub problems: Option<Vec<crate::models::Problem>>,
    /// 찾은 문제 수입니다.
    #[serde(rename = "problemCount", skip_serializing_if = "Option::is_none")]
    pub problem_count: Option<i64>,
    /// 찾은 사용자 목록입니다.
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<crate::models::User>>,
    /// 찾은 사용자 수입니다.
    #[serde(rename = "userCount", skip_serializing_if = "Option::is_none")]
    pub user_count: Option<i64>,
    /// 찾은 태그 목록입니다.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::ProblemTag>>,
    /// 찾은 태그 수입니다.
    #[serde(rename = "tagCount", skip_serializing_if = "Option::is_none")]
    pub tag_count: Option<i64>,
}

impl InlineResponse20012 {
    pub fn new() -> InlineResponse20012 {
        InlineResponse20012 {
            autocomplete: None,
            problems: None,
            problem_count: None,
            users: None,
            user_count: None,
            tags: None,
            tag_count: None,
        }
    }
}


