/*
 * @solvedac/unofficial-documentation
 *
 * 이 프로젝트는 [solved.ac](https://solved.ac/) API를 문서화하는 커뮤니티 프로젝트입니다.  이 저장소는 원작자의 요청에 따라 언제든 지워질 수 있으며, 현재 API와 일치하지 않을 수도 있는 점 양해 부탁드립니다.   <sup>   solved.ac 서비스는 shiftpsh가 기획·개발·디자인·운영하는 프로젝트로,   이 저장소와는 solved.ac의 API를 문서화해둔 것 이외에는 아무런 관련이 없습니다. </sup>   [GitHub에서 보기](https://github.com/solvedac/unofficial-documentation)   **주의**: (2023/03/08~) CORS 문제로 인해 API는 사이트 내에서 호출할 수 없으므로 별도 도구를 이용해주십시오. ([#51](https://github.com/solvedac/unofficial-documentation/issues/51)) <br> **참고**: 본 저장소를 내려받고, `pnpm dev`를 실행하시면 로컬 개발 서버를 프록시로 삼아 CORS를 무시할 수 있습니다.    ![@solvedac/unofficial-documentation banner](./assets/solvedac-ud-compact.png)
 *
 * The version of the OpenAPI document: 3ce78c7
 * Contact: me@ranolp.dev
 * Generated by: https://openapi-generator.tech
 */

/// Problem : 문제 정보입니다.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Problem {
    /// 백준 문제 번호로, 문제마다 고유합니다.
    #[serde(rename = "problemId")]
    pub problem_id: i32,
    /// 한국어 문제 제목입니다. HTML 엔티티나 LaTeX 수식을 포함할 수 있습니다.
    #[serde(rename = "titleKo")]
    pub title_ko: String,
    /// 언어별 문제 제목 목록입니다.
    #[serde(rename = "titles")]
    pub titles: Vec<crate::models::ProblemTitleTranslated>,
    /// 채점 가능 여부입니다.
    #[serde(rename = "isSolvable")]
    pub is_solvable: bool,
    /// 부분 점수/서브태스크 문제 여부입니다.
    #[serde(rename = "isPartial")]
    pub is_partial: bool,
    /// 맞은 사람 수입니다.
    #[serde(rename = "acceptedUserCount")]
    pub accepted_user_count: i32,
    #[serde(rename = "level")]
    pub level: crate::models::ProblemLevel,
    /// 난이도 기여자 수입니다.
    #[serde(rename = "votedUserCount")]
    pub voted_user_count: i32,
    /// 새싹 문제 여부입니다.
    #[serde(rename = "sprout")]
    pub sprout: bool,
    /// 레이팅을 주지 않는지 여부입니다.
    #[serde(rename = "givesNoRating")]
    pub gives_no_rating: bool,
    /// 난이도 기여 제한 여부입니다.
    #[serde(rename = "isLevelLocked")]
    pub is_level_locked: bool,
    /// 평균 시도 횟수입니다.
    #[serde(rename = "averageTries")]
    pub average_tries: f64,
    /// 공식 문제 여부입니다. 번외 문제 등은 비공식 문제로 분류됩니다.
    #[serde(rename = "official")]
    pub official: bool,
    /// 태그 목록입니다.
    #[serde(rename = "tags")]
    pub tags: Vec<crate::models::ProblemTag>,
    #[serde(rename = "metadata")]
    pub metadata: Option<serde_json::Value>,
}

impl Problem {
    /// 문제 정보입니다.
    pub fn new(problem_id: i32, title_ko: String, titles: Vec<crate::models::ProblemTitleTranslated>, is_solvable: bool, is_partial: bool, accepted_user_count: i32, level: crate::models::ProblemLevel, voted_user_count: i32, sprout: bool, gives_no_rating: bool, is_level_locked: bool, average_tries: f64, official: bool, tags: Vec<crate::models::ProblemTag>, metadata: Option<serde_json::Value>) -> Problem {
        Problem {
            problem_id,
            title_ko,
            titles,
            is_solvable,
            is_partial,
            accepted_user_count,
            level,
            voted_user_count,
            sprout,
            gives_no_rating,
            is_level_locked,
            average_tries,
            official,
            tags,
            metadata,
        }
    }
}


