/*
 * @solvedac/unofficial-documentation
 *
 * 이 프로젝트는 [solved.ac](https://solved.ac/) API를 문서화하는 커뮤니티 프로젝트입니다. 이 저장소는 원작자의 요청에 따라 언제든 지워질 수 있으며, 현재 API와 일치하지 않을 수도 있는 점 양해 부탁드립니다.  <sup>   solved.ac 서비스는 shiftpsh가 기획·개발·디자인·운영하는 프로젝트로,   이 저장소와는 solved.ac의 API를 문서화해둔 것 이외에는 아무런 관련이 없습니다. </sup>  [GitHub에서 보기](https://github.com/solvedac/unofficial-documentation)  ![@solvedac/unofficial-documentation banner](./assets/solvedac-ud-compact.png) 
 *
 * The version of the OpenAPI document: 3.2021.09+b2
 * Contact: public.ranolp@gmail.com
 * Generated by: https://openapi-generator.tech
 */

/// Schema8 : 난이도 아이콘 표시 정책입니다.

/// 난이도 아이콘 표시 정책입니다.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Schema8 {
    #[serde(rename = "default")]
    Default,
    #[serde(rename = "hide-warn")]
    HideWarn,
    #[serde(rename = "hide")]
    Hide,

}

impl ToString for Schema8 {
    fn to_string(&self) -> String {
        match self {
            Self::Default => String::from("default"),
            Self::HideWarn => String::from("hide-warn"),
            Self::Hide => String::from("hide"),
        }
    }
}




