/*
 * @solvedac/unofficial-documentation
 *
 * 이 프로젝트는 [solved.ac](https://solved.ac/) API를 문서화하는 커뮤니티 프로젝트입니다. 이 저장소는 원작자의 요청에 따라 언제든 지워질 수 있으며, 현재 API와 일치하지 않을 수도 있는 점 양해 부탁드립니다.  <sup>   solved.ac 서비스는 shiftpsh가 기획·개발·디자인·운영하는 프로젝트로,   이 저장소와는 solved.ac의 API를 문서화해둔 것 이외에는 아무런 관련이 없습니다. </sup>  **주의**: account 하위 루트를 탐색할 경우, 현재 로그인된 solvedacToken이 노출·오용될 수 있으니 주의하십시오.  [GitHub에서 보기](https://github.com/solvedac/unofficial-documentation)  ![@solvedac/unofficial-documentation banner](./assets/solvedac-ud-compact.png) 
 *
 * The version of the OpenAPI document: 3.2021.09+b2
 * Contact: public.ranolp@gmail.com
 * Generated by: https://openapi-generator.tech
 */

/// UserBackground : 사용자의 배경 사진입니다.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserBackground {
    /// 배경의 고유 ID입니다.
    #[serde(rename = "backgroundId", skip_serializing_if = "Option::is_none")]
    pub background_id: Option<String>,
    /// 배경 사진으로 가는 하이퍼링크입니다.
    #[serde(rename = "backgroundImageUrl", skip_serializing_if = "Option::is_none")]
    pub background_image_url: Option<String>,
    /// 배경의 제작자를 표시하는 문구입니다.
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    /// 배경의 제작자와 관련된 사이트로 가는 하이퍼링크입니다.
    #[serde(rename = "authorUrl", skip_serializing_if = "Option::is_none")]
    pub author_url: Option<String>,
    /// 배경의 이름입니다.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// 배경의 설명입니다.
    #[serde(rename = "displayDescription", skip_serializing_if = "Option::is_none")]
    pub display_description: Option<String>,
}

impl UserBackground {
    /// 사용자의 배경 사진입니다.
    pub fn new() -> UserBackground {
        UserBackground {
            background_id: None,
            background_image_url: None,
            author: None,
            author_url: None,
            display_name: None,
            display_description: None,
        }
    }
}


