/*
 * @solvedac/unofficial-documentation
 *
 * 이 프로젝트는 [solved.ac](https://solved.ac/) API를 문서화하는 커뮤니티 프로젝트입니다.  이 저장소는 원작자의 요청에 따라 언제든 지워질 수 있으며, 현재 API와 일치하지 않을 수도 있는 점 양해 부탁드립니다.   <sup>   solved.ac 서비스는 shiftpsh가 기획·개발·디자인·운영하는 프로젝트로,   이 저장소와는 solved.ac의 API를 문서화해둔 것 이외에는 아무런 관련이 없습니다. </sup>   [GitHub에서 보기](https://github.com/solvedac/unofficial-documentation)   **주의**: (2023/03/08~) CORS 문제로 인해 API는 사이트 내에서 호출할 수 없으므로 별도 도구를 이용해주십시오. ([#51](https://github.com/solvedac/unofficial-documentation/issues/51)) <br> **참고**: 본 저장소를 내려받고, `pnpm dev`를 실행하시면 로컬 개발 서버를 프록시로 삼아 CORS를 무시할 수 있습니다.    ![@solvedac/unofficial-documentation banner](./assets/solvedac-ud-compact.png)
 *
 * The version of the OpenAPI document: 3.2024.03+b1
 * Contact: me@ranolp.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyCredentialsUserSettings {
    #[serde(rename = "twitterPostOnProblemSolve")]
    pub twitter_post_on_problem_solve: TwitterPostOnProblemSolve,
    #[serde(rename = "screenTheme")]
    pub screen_theme: ScreenTheme,
    #[serde(rename = "twitterPostHandle")]
    pub twitter_post_handle: TwitterPostHandle,
    #[serde(rename = "twitterPostOnRatingIncrease")]
    pub twitter_post_on_rating_increase: TwitterPostOnRatingIncrease,
    #[serde(rename = "twitterPostOnTierIncrease")]
    pub twitter_post_on_tier_increase: TwitterPostOnTierIncrease,
    #[serde(rename = "twitterPostOnClassIncrease")]
    pub twitter_post_on_class_increase: TwitterPostOnClassIncrease,
    #[serde(rename = "pro_hideAds")]
    pub pro_hide_ads: ProHideAds,
    #[serde(rename = "siteLanguage")]
    pub site_language: SiteLanguage,
    #[serde(rename = "showIllustBackground")]
    pub show_illust_background: ShowIllustBackground,
    #[serde(rename = "showMovieBackground")]
    pub show_movie_background: ShowMovieBackground,
}

impl VerifyCredentialsUserSettings {
    pub fn new(twitter_post_on_problem_solve: TwitterPostOnProblemSolve, screen_theme: ScreenTheme, twitter_post_handle: TwitterPostHandle, twitter_post_on_rating_increase: TwitterPostOnRatingIncrease, twitter_post_on_tier_increase: TwitterPostOnTierIncrease, twitter_post_on_class_increase: TwitterPostOnClassIncrease, pro_hide_ads: ProHideAds, site_language: SiteLanguage, show_illust_background: ShowIllustBackground, show_movie_background: ShowMovieBackground) -> VerifyCredentialsUserSettings {
        VerifyCredentialsUserSettings {
            twitter_post_on_problem_solve,
            screen_theme,
            twitter_post_handle,
            twitter_post_on_rating_increase,
            twitter_post_on_tier_increase,
            twitter_post_on_class_increase,
            pro_hide_ads,
            site_language,
            show_illust_background,
            show_movie_background,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TwitterPostOnProblemSolve {
    #[serde(rename = "true")]
    _True,
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ScreenTheme {
    #[serde(rename = "default")]
    Default,
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TwitterPostHandle {
    #[serde(rename = "true")]
    _True,
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TwitterPostOnRatingIncrease {
    #[serde(rename = "true")]
    _True,
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TwitterPostOnTierIncrease {
    #[serde(rename = "true")]
    _True,
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TwitterPostOnClassIncrease {
    #[serde(rename = "true")]
    _True,
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProHideAds {
    #[serde(rename = "true")]
    _True,
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SiteLanguage {
    #[serde(rename = "ko")]
    Ko,
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ShowIllustBackground {
    #[serde(rename = "true")]
    _True,
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ShowMovieBackground {
    #[serde(rename = "true")]
    _True,
}

